package poly.cafe.ui;

import javax.swing.*;

public class WelcomeJDialog extends JDialog implements WelcomeController {

    private JFrame parent;

    public WelcomeJDialog() {
        super((JFrame) null, true);
        initComponents();
        waiting();
    }

    public WelcomeJDialog(JFrame parent, boolean modal) {
        super(parent, modal); // dùng constructor của JDialog
        this.parent = parent;
        initComponents();
        waiting();
    }

    @Override
    public void waiting() {
        this.setLocationRelativeTo(null);
        new Thread(() -> {
            for (int i = 0; i <= 100; i++) {
                final int progress = i;
                SwingUtilities.invokeLater(() -> progressBar.setValue(progress));
                try {
                    Thread.sleep(50);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
            SwingUtilities.invokeLater(() -> {
                this.dispose();
                new LoginJDialog(parent, true).setVisible(true);
            });
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        lblWelcom = new javax.swing.JLabel();

        setTitle("Welcome Poly Cafe");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chau Nhat Duy\\Documents\\Java-Swing-Project\\PS44284_ChauNhatDuy_SOF2043\\PS44284_ChauNhatDuy_SOF2043\\src\\main\\java\\poly\\cafe\\icons\\trump-small.png")); // NOI18N
        jLabel1.setText("Oke");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 120, -1));

        progressBar.setForeground(new java.awt.Color(255, 102, 0));
        progressBar.setValue(40);
        progressBar.setStringPainted(true);
        jPanel1.add(progressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 740, 80));

        lblWelcom.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblWelcom.setForeground(new java.awt.Color(255, 102, 0));
        lblWelcom.setText("PolyCafe");
        jPanel1.add(lblWelcom, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 160, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomeJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> {
            JFrame hiddenFrame = new JFrame();
            hiddenFrame.setUndecorated(true);
            hiddenFrame.setSize(0, 0);
            hiddenFrame.setVisible(true);
            new WelcomeJDialog(hiddenFrame, true).setVisible(true);
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblWelcom;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables
}
