package poly.cafe.ui.component;

import java.io.File;
import java.util.function.Consumer;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import lombok.Getter;
import lombok.Setter;
import poly.cafe.util.XIcon;
import poly.cafe.util.XDialog;

public class FileJPanel extends javax.swing.JPanel {

    public FileJPanel() {
        initComponents();
        // Đặt bộ lọc cho file chooser
        fileChooser.setFileFilter(new FileNameExtensionFilter("Image files", "jpg", "png"));
        // Tạo thư mục mặc định
        ensureFolderExists();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        txtFilename = new javax.swing.JTextField();
        btnBrowse = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout(2, 0));

        txtFilename.setEnabled(false);
        add(txtFilename, java.awt.BorderLayout.CENTER);

        btnBrowse.setText("Browse...");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });
        add(btnBrowse, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            try {
                // Đảm bảo thư mục tồn tại trước khi sao chép
                ensureFolderExists();
                File file = XIcon.copyTo(selectedFile, this.folder);
                this.setFilename(file.getName());
                if (this.fileChanged != null) {
                    this.fileChanged.accept(file);
                }
            } catch (Exception e) {
                XDialog.alert("Lỗi khi sao chép file: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnBrowseActionPerformed

    private void ensureFolderExists() {
        File folderFile = new File(this.folder);
        if (!folderFile.exists()) {
            folderFile.mkdirs();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowse;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JTextField txtFilename;
    // End of variables declaration//GEN-END:variables

    @Getter
    @Setter
    String folder = "images"; // Đồng bộ với UserManagerJDialog

    @Getter
    @Setter
    Consumer<File> fileChanged;

    public String getFilename() {
        return txtFilename.getText();
    }

    public void setFilename(String filename) {
        txtFilename.setText(filename);
    }

    public File getFile() {
        return new File(folder, this.getFilename());
    }
}
