package poly.cafe.ui.component;

import java.io.File;
import java.util.function.Consumer;
import javax.swing.JFileChooser;
import lombok.Getter;
import lombok.Setter;
import poly.cafe.util.XIcon;


public class FileJPanel extends javax.swing.JPanel {


    public FileJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        txtFilename = new javax.swing.JTextField();
        btnBrowse = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout(2, 0));

        txtFilename.setEnabled(false);
        add(txtFilename, java.awt.BorderLayout.CENTER);

        btnBrowse.setText("Browse...");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });
        add(btnBrowse, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        // TODO add your handling code here:
        if(fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION){
            File selectedFile = fileChooser.getSelectedFile();
            File file = XIcon.copyTo(selectedFile, this.folder);
            this.setFilename(file.getName());
            if(this.fileChanged != null){
                this.fileChanged.accept(file);
            }
        }
    }//GEN-LAST:event_btnBrowseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowse;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JTextField txtFilename;
    // End of variables declaration//GEN-END:variables

    @Getter
    @Setter
    String folder = "files";
    Consumer<File> fileChanged;
    
    public String getFilename(){
        return txtFilename.getText();
    }
    public void setFilename(String filename){
        txtFilename.setText(filename);
    }
    public File getFile(){
        return new File(folder, this.getFilename());
    }
}
