package poly.cafe.ui.component;

import java.util.function.Consumer;
import javax.swing.JRadioButton;
import lombok.Setter;


public class RadioJPanel extends javax.swing.JPanel {


    public RadioJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        group.add(jRadioButton1);
        jRadioButton1.setText("Option 1");
        add(jRadioButton1);

        group.add(jRadioButton2);
        jRadioButton2.setText("Option 2");
        add(jRadioButton2);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup group;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    // End of variables declaration//GEN-END:variables

    JRadioButton[] radios = {};
    private Consumer<Integer> indexChanged;
    
    public void setIndexChanged(Consumer<Integer> indexChanged) {
        this.indexChanged = indexChanged;
        for (JRadioButton radio : radios) {
            radio.addActionListener((e) -> indexChanged.accept(this.getIndex()));
        }
    }

    public void setItems(String[] items) {
        this.removeAll();
        radios = new JRadioButton[items.length];
        for (int i = 0; i < radios.length; i++) {
            radios[i] = new JRadioButton(items[i]);
            this.add(radios[i]);
            group.add(radios[i]);
        }
        this.setIndex(0);
    }

    public int getIndex() {
        for(var i=0; i<radios.length; i++){
            if(radios[i].isSelected()){
                return i; 
            }
        }
        return 0;
    }
    
    public void setIndex(int index) {
        radios[index].setSelected(true);
    }
    
    public String getText() {
        int index = this.getIndex();
        return radios[index].getText();
    }
}
